services:
    laravel-filament-app:
        build: .
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: ${APP_CONTAINER_NAME}
        restart: unless-stopped
        working_dir: /var/www
        # volumes:
        #     - .:/var/www
        #     - ./.env:/var/www/.env
        #     - ./storage:/var/www/storage
        #     - ./bootstrap/cache:/var/www/bootstrap/cache
        command: >
            sh -c "php artisan storage:link && \
                    until php artisan migrate --force --seed; do sleep 3; done && \
                    php-fpm"
        networks:
            - laravel-filament_network
        env_file:
            - .env
    laravel-filament-webserver:
        image: nginx:latest
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: ${WEBSERVER_CONTAINER_NAME}
        restart: unless-stopped
        ports:
            - "127.0.0.1:${WEBSERVER_PORT}:80"
        volumes:
            - .:/var/www
            - ./public:/var/www/public
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-filament_network
    laravel-filament-redis:
        image: redis:latest
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: ${REDIS_CONTAINER_NAME}
        restart: unless-stopped
        networks:
            - laravel-filament_network
    mysql:
        image: mysql:8.4
        container_name: laravel-filament-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel-filament_network
volumes:
    db_data:
networks:
    laravel-filament_network:

